version: '3.7'
services:
  db:
    image: postgres
    container_name: godo-api-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  server:
    container_name: godo-api-server
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - GODO_API_USER=${GODO_API_USER}
      - GODO_API_PASSWORD=${GODO_API_PASSWORD}
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./godo-api-server:/app/godo-api-server
    expose:
      - 8080
    depends_on:
      - db
volumes:
  db:
  server:
