version: '3'
services:
  db:
    image: postgres
    container_name: goapi-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  server:
    container_name: goapi-server
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./goapi-server:/app/goapi-server
    expose:
      - 8080
    depends_on:
      - db
volumes:
  db:
  server:
